
#include "bsp_api.h"
#include "hal_data.h"
#include "GPT_int.h"
#include "Foc.h"

FSP_CPP_HEADER void R_BSP_WarmStart(bsp_warm_start_event_t event) BSP_PLACE_IN_SECTION(".warm_start");

short test_data = 0;

/******************************************************************************************************************
 */

/**
* main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.	This 
   function
* is called by main() when no RTOS is used.
*********************************************************************************************************************
   */
void hal_entry(void)
{
	/* TODO: add your own code here */
	//MSTPCRC register Bit1 Clear
	//GPT Unit 0 Module Release
	* ((unsigned long *) 0x80280308) &= 0xFFFFFFFBu;

	R_GPT123_IO_int();
	R_GPT123_Create();

	foc_int();

	while(1)
	{
//
//		if(test_data == 3)
//		{
//			test_data = 0;
//			PWM_CMP_UPDATE_MACRO(0x1000, 0x1000, 0x1000);
//		}
//		else if(test_data == 2)
//		{
//			test_data = 0;
//			PWM_CMP_UPDATE_MACRO(0x2000, 0x2000, 0x2000);
//		}


		__NOP();
	}

}



/******************************************************************************************************************
 */

/**
* This function is called at various points during the startup process.  This implementation uses the event that is
* called right before main() to set up the pins.
*
* @param[in]  event	Where at in the start up process the code is currently at
*********************************************************************************************************************
   */
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
	if(BSP_WARM_START_POST_C == event)
	{
		/* C runtime environment and system clocks are setup. */

		/* Configure pins. */
		R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
	}
}


