
#include "hal_data.h"
#include "GPT_int.h"

FSP_CPP_HEADER void R_BSP_WarmStart(bsp_warm_start_event_t event) BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER volatile uint32_t debugdata = 0;


/******************************************************************************************************************
	*/ /**
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.	This 
	function
 * is called by main() when no RTOS is used.
 *********************************************************************************************************************
	*/
void hal_entry(void)
{
	/* TODO: add your own code here */
	//MSTPCRC register Bit1 Clear
	//GPT Unit 0 Module Release
	* ((unsigned long *) 0x80280308) &= 0xFFFFFFFBu;


	R_GPT1_Create();
	GPT1_IO_int();

	while (1)
	{
		if (debugdata == 2)
		{
		    debugdata = 0;
			R_PORT_SR->P[19] = (uint8_t) ((R_PORT_SR->P[19]) | (0x40));
		}
		else if (debugdata == 3)
		{
		    debugdata = 0;
			R_PORT_SR->P[19] = (uint8_t) ((R_PORT_SR->P[19]) & (0xBF));
		}

		__NOP();
	}

}



/******************************************************************************************************************
	*/ /**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event	Where at in the start up process the code is currently at
 *********************************************************************************************************************
	*/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
	if (BSP_WARM_START_POST_C == event)
	{
		/* C runtime environment and system clocks are setup. */

		/* Configure pins. */
		R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
	}
}


